### ISSUE TITLE
views

### ISSUE THREAD

**Issue by berdoff** [H1B0B0/twitch-Viewerbot#10]
can u add reg views in stats stream?

**Comment by H1B0B0** [comment]
If the bot is launched with every stream, then yes, the views would be consistent. However, if you want a consistent number, it's advisable not to have too many threads running concurrently.

**Comment by berdoff** [comment]
At the moment, views are not counted in twitch statistics, and when the main_just_terminal program is launched, more than 300 streams at the same time, for some reason it does not start, although 10,000 are selected

**Comment by berdoff** [comment]
![image](https://github.com/H1B0B0/twitch-Viewerbot/assets/119667353/b6677bd6-3bda-40f5-a2cf-e6cc6ac40893)

**Comment by berdoff** [comment]
![image](https://github.com/H1B0B0/twitch-Viewerbot/assets/119667353/2882bd48-47eb-4535-867d-071f77c58f54)

**Comment by berdoff** [comment]
![image](https://github.com/H1B0B0/twitch-Viewerbot/assets/119667353/85ad3e75-6de6-4240-908d-942fb2f3318d)
Live Views zero

**Comment by Lucknite** [comment]
yeah, i think its bc its just a request, isnt ant way to make them count as
live viewers?

**Comment by H1B0B0** [comment]
Yes, @Lucknite is right, these are indeed simple requests because otherwise it would require more power.

**Comment by Lucknite** [comment]
could you make a separate version which, even taking more resources, it
would count as live viewers? id appreciate it
