### ISSUE TITLE
bot cant find proxies anymore

### ISSUE THREAD

**Issue by douglascxbx** [H1B0B0/twitch-Viewerbot#12]
the bot does not have any alive proxies :/

![image](https://github.com/H1B0B0/twitch-Viewerbot/assets/135669170/abe9f237-7bfa-4658-adb2-debca54e6817)

**Comment by H1B0B0** [comment]
Hello, it can be that the API of the proxies will block you if you send a lot of requests on it using the same connection in a short period of time. Retry later or download a proxies list.

**Comment by douglascxbx** [comment]
dunno if that is the case, i was not using it in the last days... kinda confuse lol

**Comment by douglascxbx** [comment]
i've tested in a google cloud VM, and it keeps showing 0 proxies lol

**Comment by douglascxbx** [comment]
yo my man, you dont have to sorry about anything! You're a great guy and your project is perfect, absolutelly! I'm just letting you know about the bug. Thanks for the contribution with the community and for the patience, you're a awesome guy! and if i said something wrong, sorry! English is not my first language.

**Comment by douglascxbx** [comment]
i've tested all the releases, The first release with the application on executable version is working normally xD

**Comment by H1B0B0** [comment]
Yes, the first version is not the best because the proxies have died over time.

**Comment by douglascxbx** [comment]
guess i'll just wait for a new release, thanks again for the replies <3

**Comment by H1B0B0** [comment]
Hello, sorry for the delay, a new release is in build, try it and tell me if it's fixed for you :)

**Comment by douglascxbx** [comment]
Yo, sup mate! Guess it's working fine now, had some peaks to 100% cpu but proxies working normally again! =)

**Comment by douglascxbx** [comment]
thanks alot for this! ♥

**Comment by H1B0B0** [comment]
Yes, the peak is normal at the start of the thread, but if you wait until the thread has started, the performance improves after that. Thanks for bringing up the issue, I'm here if you encounter any problems.😄
