### ISSUE TITLE
This is going to sound really dumb... but i cant find the install.bat file

### ISSUE THREAD

**Issue by shirone-afk** [H1B0B0/twitch-Viewerbot#13]
As the title says, i cant find it in the folder...

![Capture d'écran 2024-05-02 210411](https://github.com/H1B0B0/twitch-Viewerbot/assets/73953073/292cce35-c43f-4516-89fe-d0914b705635)

![Capture d'écran 2024-05-02 210426](https://github.com/H1B0B0/twitch-Viewerbot/assets/73953073/bd53b307-801e-4200-a2d1-093ae0274476)

**Comment by H1B0B0** [comment]
Hello, sorry for that. Now the bot is compiled in .exe just go in release section and download the executable 😀

**Comment by shirone-afk** [comment]
i found it thank you!
