### ISSUE TITLE
problem with linux-based systems

### ISSUE THREAD

**Issue by Deb4ikOff** [H1B0B0/twitch-Viewerbot#2]
code is running normally, but requests are not sent. Tried many times, and different pc/phones, only works correctly on windows. What i need to do??

**Comment by oktwme** [comment]
same

**Comment by H1B0B0** [comment]
Hello, sorry for that. I test my code on Linux by a raspi 4B. I don't have problem with him, but i go watch what is the problem and try to solve him. On linux you use the source code it's right? Can you give me more informations or not?

**Comment by H1B0B0** [comment]
I don't detect any errors. Can you give me more informations please ?

**Comment by H1B0B0** [comment]
Hello, I don't understand the question at the moment. But i gonna to try more information about your bug.

**Comment by Deb4ikOff** [comment]
I'm used Ubuntu 22.04 LTS and Linux Mint. Yes, I used source code, and installed all needed libraries. Counter of sent packets doesn't increase. (Sorry for bad speaking)

**Comment by H1B0B0** [comment]
Can you make a git clone for updated this folder? Now maybe it's fixed, i maked some fixe in this week. Try to clone and give me information. Do you have install the pyproject dependencies?
