### ISSUE TITLE
how to use my own proxies on terminal use?

### ISSUE THREAD

**Issue by italohugo** [H1B0B0/twitch-Viewerbot#3]
I'd like do import my proxies list when running as terminal, and not by GUI. Is there a way to include on terminal some input : "upload your proxies on txt". Thanks

**Comment by H1B0B0** [comment]
Hello, this is not possible at the moment but I will work on it if necessary.

**Comment by H1B0B0** [comment]
Hello, sorry for the delay. I have addressed your issue and improved the terminal version. Thank you for your patience.
