### ISSUE TITLE
cpu at 100%

### ISSUE THREAD

**Issue by douglascxbx** [H1B0B0/twitch-Viewerbot#5]
yo, sup! program is working and looking great, but my cpu goes to 100% everytime i use it, is it a bug or i messed up in something?
my pc is a ryzen 5 3600 with 16gb of ram.

**Comment by H1B0B0** [comment]
Hello, thank you for bringing the issue to my attention. I'll make sure to address it promptly.

**Comment by H1B0B0** [comment]
Hello, thank you for the wait. The performance and stability have been increased. I'm going to close this issue. If you encounter the problem again, please send me more information.
