### ISSUE TITLE
There is no issue in your project.... every thing Is Prefect .Read Me....   

### ISSUE THREAD

**Issue by RatPython1** [H1B0B0/twitch-Viewerbot#9]
SIr i have question there is two more Live stream plat form **Can you make these Views Bots of this website**
++++++++++++++++++++++
**One Is Rumble LiveStream**
https://rumble.com/
++++++++++++++++++++++
**2and Is This One : vkplay**
 https://vkplay.live/
===================================
 Every thing and your project is 100% good Works fines 🥰

**Comment by H1B0B0** [comment]
Hello, maybe I can try it. I have watched and I see I can do it easily for VK Play, but maybe it's more difficult for Rumble.

**Comment by RatPython1** [comment]
Thank you for feedback you can create it for vk i am waiting for vk also sir your Discord not working Thank you
when you have free time then make ok other wise all ok
